### PR TITLE
Update version of multiapps plugin to 3.1.1

### PR DESCRIPTION
**Pull request by theghost5800**

### CODE REVIEW

**Comment by boyan-velinov** [comment]
The change is needed because there is a high chances of problems during upload of larger MTA archives to MTA Deployment Service. This is due to recent changes in MTA deployment Service related to file processing.

WIth the new MultiApps CF CLI plugin MTA upload for file parts is done sequentially and it mitigates the risk for larger MTA archives and/or latency:
https://github.com/cloudfoundry/multiapps-cli-plugin/releases/tag/v3.1.1

**Review by o-liver — APPROVED** [review]
Thanks for that!

**Comment by theghost5800** [comment]
@o-liver I don't see how I can accept the license/cla? Could you please provide a link.

**Comment by o-liver** [comment]
> @o-liver I don't see how I can accept the license/cla? Could you please provide a link.

I don't know, unfortunately. I will solve it now by providing a new PR. Seems as if one cannot simply open a PR from a fork.
Do you know of this issue @radsoulbeard ?

**Comment by o-liver** [comment]
Me opening the PR did not fix the issue. I will investigate ASAP.

**Comment by o-liver** [comment]
@theghost5800 Could you try with this link if it helps? https://cla-assistant.io/SAP/devops-docker-cf-cli?pullRequest=60

**Comment by o-liver** [comment]
> @o-liver I had tried to sign the license multiple times but it looks like it doesn't work, check it's still present. When I go to the provided link, I can see now "You have agreed to the CLA for SAP/devops-docker-cf-cli".

Same for me, I need to find out what is going on here! Will keep you posted.

**Comment by srinikitha09** [comment]
> MultiApps CF CLI p

Is this a new change that we need to do now?

**Comment by anilkeshav27** [comment]
@o-liver ,  is there a new docker image released ? or are the changes under `ppiper/cf-cli:latest` , so piper does not change ?

**Comment by o-liver** [comment]
> @o-liver , is there a new docker image released ? or are the changes under `ppiper/cf-cli:latest` , so piper does not change ?

@anilkeshav27 [In the Piper Cloud Foundry steps we are using the latest tag,](https://github.com/search?q=repo%3ASAP%2Fjenkins-library+ppiper%2Fcf-cli&type=code&p=1) so we will automatically use the new release.

@DanielMieg @tiloKo @ranliii In the ABAP steps you are fixed on [ppiper/cf-cli:v12](https://github.com/search?q=repo%3ASAP%2Fjenkins-library+ppiper%2Fcf-cli%3Av12&type=code), which is one year old. We are now at v16, maybe this is something you want to update.

**Pull request merged**
