### PR TITLE
update cf cli to version 7.2

### LINKED ISSUE #31: cf-cli is still the deprecated v6
The CLI downloaded is still the v6 version, while this one has been deprecated for CF at the 5th of November:
https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2020-11-04&to=2020-11-06

### PR DESCRIPTION
**Pull request by radsoulbeard**
- update mta plugin to 2.5.1
- remove create service plugin as contained in cf cli v7

fixes #31

### CODE REVIEW

**Comment by fwilhe** [comment]
Hi @radsoulbeard 

are you sure this is not a breaking change for existing pipelines? I don't have the time to do an in depth review, and I'm not an active CF user (anymore), so I'm probably not the best reviewer here.

Looping in @marcusholl @CCFenner 

Can you judge if this breaks anything?

**Comment by marcusholl** [comment]
> Can you judge if this breaks anything?

No. Not close enough to cf use-cases. We should have test cases, I suppose ...

**Comment by radsoulbeard** [comment]
> Hi @radsoulbeard
> 
> are you sure this is not a breaking change for existing pipelines? I don't have the time to do an in depth review, and I'm not an active CF user (anymore), so I'm probably not the best reviewer here.
> 
> Looping in @marcusholl @CCFenner
> 
> Can you judge if this breaks anything?

Creating a new image version does not mean to change the defaults in the Piper library immediately. The integration tests passed.

**Comment by marcusholl** [comment]
@radsoulbeard 

> does not mean to change the defaults in the Piper library immediately

Can you clarify that? As far as I can see we have configured `ppiper/cf-cli` [here](https://github.com/SAP/jenkins-library/blob/master/resources/default_pipeline_environment.yml#L214) and some lines below. Since there is no explicit version we use latest, I suppose. That means if there is a new cf-cli docker image that-one will be used. Am I wrong?

Maybe we recommend to the customers to configure fixed versions, but by default there is no fixed version.

**Comment by radsoulbeard** [comment]
@marcusholl 
You are right, that will pull latest. We need to test that carefully.

**Comment by radsoulbeard** [comment]
[testResults.txt](https://github.com/SAP/devops-docker-cf-cli/files/5873029/testResults.txt)
I tested all additional steps with the new version. cloudFoundryCreateSpace, cloudFoundryCreateService, cloudFoundryCreateServiceKey, cloudFoundryDeleteService and cloudFoundryDeleteSpace still works.

**Comment by radsoulbeard** [comment]
As discussed, SAP/jenkins-library defaults are now on a dedicated tag v5
Temporary fix ppiper/cf-cli version SAP/jenkins-library#2541

**Review by OliverNocon — APPROVED** [review]
LGTM

**Pull request merged**
