### PR TITLE
Use new debian bookworm base image

### PR DESCRIPTION
**Pull request by o-liver**
Also upgraded mta plugin version to latest

### CODE REVIEW

**Comment by o-liver** [comment]
@radsoulbeard Is the Infrastructure test still valid. I see it tries to run [this Jenkinsfile](https://github.com/piper-validation/cloud-s4-sdk-book/blob/validate-cf-cli/Jenkinsfile), which uses the old sdk pipeline library v24.

**Comment by o-liver** [comment]
I see we had this discussion about the Infrastructure Tests already in PR #55 Time to remove those tests. Would be nice to replace them with something else though. Would it be enough to pull the image and do a `cf --version` check inside the container?

**Comment by srinikitha09** [comment]
Did you have a chance to test these changes on one of our reference apps?

**Comment by o-liver** [comment]
> Did you have a chance to test these changes on one of our reference apps?

No, is that best practice? I should build it myself and test it? I would do so locally in that case, not with our service.

**Comment by o-liver** [comment]
I would argue that we should keep the image up to date in any case. Testing it on one of our sample applications does not prove much and this update is necessary anyhow: We cannot stay on an old debian; We should not let the plugins used get old.

**Comment by srinikitha09** [comment]
> > Did you have a chance to test these changes on one of our reference apps?
> 
> No, is that best practice? I should build it myself and test it? I would do so locally in that case, not with our service.

AFAIK, that is how we do so that we are aware of the issues beforehand.

**Comment by srinikitha09** [comment]
> I would argue that we should keep the image up to date in any case. Testing it on one of our sample applications does not prove much and this update is necessary anyhow: We cannot stay on an old debian; We should not let the plugins used get old.

Yes, agree, but still it would be worthy to test it on our side as well.

**Comment by o-liver** [comment]
> 

Ok, I will do so and let you know

**Comment by o-liver** [comment]
> > I would argue that we should keep the image up to date in any case. Testing it on one of our sample applications does not prove much and this update is necessary anyhow: We cannot stay on an old debian; We should not let the plugins used get old.
> 
> Yes, agree, but still it would be worthy to test it on our side as well.

Tested it locally and it works:

- [ ] cf login works
- [ ] cf deploy of mta archive works

**Review by srinikitha09 — APPROVED** [review]
Looks good

**Pull request merged**
